services:
  - type: web
    name: blaupunkt-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: DESTINATION_EMAIL
        value: info@blaupunkt-ev.com
      - key: VITE_DOMAIN
        sync: false
