services:
  # Backend Email Service Only
  # Frontend is hosted on Hostinger
  - type: web
    name: blaupunkt-backend
    runtime: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node mailserver.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SMTP_HOST
        value: smtp.hostinger.com
      - key: SMTP_PORT
        value: 465
      - key: SMTP_USER
        sync: false  # Set this manually in Render dashboard
      - key: SMTP_PASS
        sync: false  # Set this manually in Render dashboard
      - key: DESTINATION_EMAIL
        value: info@blaupunkt-ev.com
      - key: PORT
        value: 5000
      - key: VITE_DOMAIN
        value: https://blaupunkt-ev.com
    healthCheckPath: /api/health
