name: Keep Render Backend Alive

on:
  schedule:
    # Run every 12 minutes (5 times per hour)
    # This keeps the Render free tier from sleeping (15 min timeout)
    - cron: '*/12 * * * *'
  
  workflow_dispatch: # Allow manual trigger

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Render Backend
        run: |
          echo "🏓 Pinging backend to keep it alive..."
          
          # Health check endpoint (add this to your backend if needed)
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET https://blaupunkt-backend.onrender.com/api/health \
            --max-time 30)
          
          if [ $response -eq 200 ] || [ $response -eq 404 ]; then
            echo "✅ Backend is alive! (HTTP $response)"
          else
            echo "⚠️ Backend responded with HTTP $response"
            # Still exit 0 to not fail the workflow
            exit 0
          fi
      
      - name: Log timestamp
        run: echo "Last ping at $(date -u)"
